# Orchestrator Agent Behavior Configuration
#
# This file defines which behaviors are enabled for the Orchestrator agent
# and their configuration parameters.
#
# The Orchestrator manages high-level task delegation and architecture consultation.

behaviors:
  # Context Management
  # CompactWhenNearFullBehavior provides append-until-full context management
  - type: CompactWhenNearFullBehavior
    params:
      max_tokens: 8000
      compact_threshold: 0.75

  # Utility Behaviors
  # LoopDetectionBehavior detects repeated actions
  - type: LoopDetectionBehavior
    params:
      max_repeats: 5

  # NOTE: The following behaviors are not yet implemented (Phase 2 work):
  # - DelegationBehavior (provides task delegation to Architect and TaskExecutor)
  # - ClarificationBehavior (provides user interaction tools)
  # - WorkspaceToolsBehavior (provides workspace management)
  # - JetboxNotesBehavior (provides persistent context summaries)
  # - StatusDisplayBehavior (renders progress and performance stats)
  # - TaskManagementBehavior (provides task breakdown and tracking)
