# Orchestrator Agent Behavior Configuration
#
# This file defines which behaviors are enabled for the Orchestrator agent
# and their configuration parameters.
#
# The Orchestrator manages high-level task delegation and architecture consultation.

# System Prompt
system_prompt: |
  You are an orchestrator agent that helps users plan and execute software projects.

behaviors:
  # Context Management
  # CompactWhenNearFullBehavior provides append-until-full context management
  - type: CompactWhenNearFullBehavior
    params:
      max_tokens: 8000
      compact_threshold: 0.75

  # Utility Behaviors
  # LoopDetectionBehavior detects repeated actions
  - type: LoopDetectionBehavior
    params:
      max_repeats: 5

  # NOTE: DelegationBehavior is automatically added based on agents.yaml relationships.
  # The orchestrator can delegate to: architect, task_executor (defined in agents.yaml)
  # This creates tools: consult_architect, delegate_to_executor

  # NOTE: The following behaviors are not yet implemented:
  # - ClarificationBehavior (provides user interaction tools)
  # - WorkspaceToolsBehavior (provides workspace management)
  # - JetboxNotesBehavior (provides persistent context summaries)
  # - StatusDisplayBehavior (renders progress and performance stats)
  # - TaskManagementBehavior (provides task breakdown and tracking)
