# Orchestrator Agent Behavior Configuration
#
# This file defines which behaviors are enabled for the Orchestrator agent
# and their configuration parameters.
#
# The Orchestrator manages high-level task delegation and architecture consultation.

# Agent Blurb (3-5 sentences describing specialty/purpose for parent agents)
# If not specified, uses blurb from agents.yaml
blurb: |
  Orchestrator manages user conversations and coordinates work delegation.
  It assesses task complexity, clarifies requirements, and delegates to
  appropriate specialist agents (Architect for design, TaskExecutor for
  implementation). Best for project planning, task breakdown, and managing
  multi-step workflows requiring coordination between different agents.

# System Prompt
system_prompt: |
  You are an orchestrator agent that helps users plan and execute software projects.


behaviors:
  # Context Management
  # CompactWhenNearFullBehavior provides append-until-full context management
  - type: CompactWhenNearFullBehavior

  # Utility Behaviors
  # LoopDetectionBehavior detects repeated actions
  - type: LoopDetectionBehavior

  # NOTE: DelegationBehavior is automatically added based on agents.yaml relationships.
  # The orchestrator can delegate to: architect, task_executor (defined in agents.yaml)
  # This creates tools: consult_architect, delegate_to_executor

  # NOTE: The following behaviors are not yet implemented:
  # - ClarificationBehavior (provides user interaction tools)
  # - WorkspaceToolsBehavior (provides workspace management)
  # - WorkspaceTaskNotesBehavior (provides persistent context summaries)
  # - StatusDisplayBehavior (renders progress and performance stats)
  # - TaskManagementBehavior (provides task breakdown and tracking)
