# Task Executor Agent Behavior Configuration
#
# This file defines which behaviors are enabled for the TaskExecutor agent
# and their configuration parameters.
#
# Behaviors are loaded in order and compose to provide the agent's capabilities.

behaviors:
  # Context Management
  # SubAgentContextBehavior provides delegated work context management
  - type: SubAgentContextBehavior
    params:
      max_tokens: 128000  # High token limit for complex delegated tasks

  # Tool Behaviors
  # FileToolsBehavior provides file read/write/list operations
  - type: FileToolsBehavior
    params: {}

  # CommandToolsBehavior provides bash command execution
  - type: CommandToolsBehavior
    params:
      whitelist:
        - python
        - pytest
        - ruff
        - pip

  # ServerToolsBehavior provides server start/stop/check operations
  - type: ServerToolsBehavior
    params: {}

  # Utility Behaviors
  # LoopDetectionBehavior detects repeated actions (infinite loops)
  - type: LoopDetectionBehavior
    params:
      max_repeats: 5  # Warn after 5 identical actions

  # JetboxNotesBehavior provides persistent context summaries
  - type: JetboxNotesBehavior
    params:
      enabled: true

  # StatusDisplayBehavior renders progress and performance stats
  - type: StatusDisplayBehavior
    params:
      show_hierarchy: true
