# GENERATED BY METAPROGRAMMER - Safe to delete for testing
import pytest

# Adjust the import path according to your project structure
from json_tools_behavior import JsonToolsBehavior


@pytest.fixture
def behavior():
    """Instantiate the JsonToolsBehavior for use in tests."""
    return JsonToolsBehavior()


def test_parse_json_success(behavior):
    """Test that parse_json correctly parses a valid JSON string."""
    json_str = '{"name": "Alice", "age": 30}'
    result = behavior.parse_json(json_str)
    assert isinstance(result, dict), "Result should be a dictionary"
    assert result == {"name": "Alice", "age": 30}, "Parsed data does not match expected output"


def test_parse_json_error(behavior):
    """Test that parse_json returns an error dict for invalid JSON."""
    invalid_json = '{"name": "Alice", "age": 30'  # Missing closing brace
    result = behavior.parse_json(invalid_json)
    assert isinstance(result, dict), "Result should be a dictionary"
    assert "error" in result, "Error key should be present in the result"
    assert isinstance(result["error"], str), "Error message should be a string"


def test_format_json_default_indent(behavior):
    """Test that format_json formats data with default indentation."""
    data = {"name": "Bob", "age": 25}
    json_str = behavior.format_json(data)
    expected = '{\n  "name": "Bob",\n  "age": 25\n}'
    assert json_str == expected, "Formatted JSON does not match expected output with default indent"


def test_format_json_custom_indent(behavior):
    """Test that format_json respects a custom indentation level."""
    data = {"name": "Carol", "age": 28}
    json_str = behavior.format_json(data, indent=4)
    expected = '{\n    "name": "Carol",\n    "age": 28\n}'
    assert json_str == expected, "Formatted JSON does not match expected output with custom indent"


def test_validate_json_schema_success(behavior):
    """Test that validate_json_schema passes when data matches the schema."""
    data = {"name": "Dave", "age": 40}
    schema = {
        "required": ["name", "age"],
        "properties": {
            "name": {"type": "string"},
            "age": {"type": "integer"},
        },
    }
    result = behavior.validate_json_schema(data, schema)
    assert result is True, "Validation should succeed for matching data"


def test_validate_json_schema_error_missing_property(behavior):
    """Test that validate_json_schema fails when a required property is missing."""
    data = {"name": "Eve"}  # Missing 'age'
    schema = {
        "required": ["name", "age"],
        "properties": {
            "name": {"type": "string"},
            "age": {"type": "integer"},
        },
    }
    result = behavior.validate_json_schema(data, schema)
    assert isinstance(result, dict), "Result should be a dictionary on failure"
    assert "error" in result, "Error key should be present in the result"
    assert "missing required property" in result["error"].lower(), "Error message should indicate missing property"


def test_validate_json_schema_error_wrong_type(behavior):
    """Test that validate_json_schema fails when a property has the wrong type."""
    data = {"name": "Frank", "age": "forty"}  # 'age' should be integer
    schema = {
        "required": ["name", "age"],
        "properties": {
            "name": {"type": "string"},
            "age": {"type": "integer"},
        },
    }
    result = behavior.validate_json_schema(data, schema)
    assert isinstance(result, dict), "Result should be a dictionary on failure"
    assert "error" in result, "Error key should be present in the result"
    assert "type mismatch" in result["error"].lower(), "Error message should indicate type mismatch"