# META: AUTHOR=MetaProgrammer
# META: GENERATOR=CreateBehaviorBehavior
# META: TIMESTAMP=2025-11-07T01:06:47.322806
# META: PARENT_REQUEST="Provides basic arithmetic calculation tools (add, subtract, multiply, divide)"
# GENERATED BY METAPROGRAMMER - Safe to delete for testing
import pytest

# Import the behavior class (adjust the import path as needed)
from calculator_behavior import CalculatorBehavior


@pytest.fixture
def calculator():
    """Instantiate a CalculatorBehavior object for use in tests."""
    return CalculatorBehavior()


# ---------- Add Tool Tests ----------

def test_add_success_integers(calculator):
    """Test that adding two integers returns the correct sum."""
    result = calculator.add(a=3, b=5)
    assert result == 8, "Adding 3 and 5 should return 8"


def test_add_success_floats(calculator):
    """Test that adding two floats returns the correct sum."""
    result = calculator.add(a=2.5, b=4.1)
    assert pytest.approx(result, 1e-7) == 6.6, "Adding 2.5 and 4.1 should return 6.6"


def test_add_success_negative(calculator):
    """Test that adding negative numbers works correctly."""
    result = calculator.add(a=-7, b=-3)
    assert result == -10, "Adding -7 and -3 should return -10"


def test_add_error_non_numeric(calculator):
    """Test that passing non-numeric arguments raises a TypeError."""
    with pytest.raises(TypeError):
        calculator.add(a="foo", b=2)
    with pytest.raises(TypeError):
        calculator.add(a=3, b=None)


def test_add_error_missing_argument(calculator):
    """Test that missing required arguments raise a TypeError."""
    with pytest.raises(TypeError):
        calculator.add(a=1)  # Missing 'b'
    with pytest.raises(TypeError):
        calculator.add(b=2)  # Missing 'a'


# ---------- Subtract Tool Tests ----------

def test_subtract_success_integers(calculator):
    """Test that subtracting two integers returns the correct difference."""
    result = calculator.subtract(a=10, b=4)
    assert result == 6, "Subtracting 4 from 10 should return 6"


def test_subtract_success_floats(calculator):
    """Test that subtracting two floats returns the correct difference."""
    result = calculator.subtract(a=5.5, b=2.2)
    assert pytest.approx(result, 1e-7) == 3.3, "Subtracting 2.2 from 5.5 should return 3.3"


def test_subtract_success_negative(calculator):
    """Test that subtracting with negative numbers works correctly."""
    result = calculator.subtract(a=-5, b=-10)
    assert result == 5, "Subtracting -10 from -5 should return 5"


def test_subtract_error_non_numeric(calculator):
    """Test that passing non-numeric arguments raises a TypeError."""
    with pytest.raises(TypeError):
        calculator.subtract(a="bar", b=1)
    with pytest.raises(TypeError):
        calculator.subtract(a=2, b="baz")


def test_subtract_error_missing_argument(calculator):
    """Test that missing required arguments raise a TypeError."""
    with pytest.raises(TypeError):
        calculator.subtract(a=7)  # Missing 'b'
    with pytest.raises(TypeError):
        calculator.subtract(b=3)  # Missing 'a'