# GENERATED BY METAPROGRAMMER - Safe to delete for testing
import os
import pytest

from environment_behavior import EnvironmentBehavior


@pytest.fixture
def env_behavior():
    """Instantiate the EnvironmentBehavior class."""
    return EnvironmentBehavior()


def test_get_env_var_success_existing(env_behavior, monkeypatch):
    """Test retrieving an existing environment variable."""
    monkeypatch.setenv("TEST_VAR", "value123")
    result = env_behavior.get_env_var(name="TEST_VAR")
    assert result == "value123", "Should return the value of the existing env var"


def test_get_env_var_success_default(env_behavior, monkeypatch):
    """Test retrieving a non‑existent variable with a default value."""
    monkeypatch.delenv("NON_EXISTENT_VAR", raising=False)
    result = env_behavior.get_env_var(name="NON_EXISTENT_VAR", default="default_value")
    assert result == "default_value", "Should return the provided default when var is missing"


def test_get_env_var_error_missing_no_default(env_behavior, monkeypatch):
    """Test that missing variable without default raises KeyError."""
    monkeypatch.delenv("MISSING_VAR", raising=False)
    with pytest.raises(KeyError):
        env_behavior.get_env_var(name="MISSING_VAR")


def test_set_env_var_success(env_behavior, monkeypatch):
    """Test setting an environment variable and retrieving it."""
    env_behavior.set_env_var(name="NEW_VAR", value="new_value")
    # Directly check os.environ to ensure the variable was set
    assert os.environ["NEW_VAR"] == "new_value"
    # Retrieve via the behavior to confirm consistency
    retrieved = env_behavior.get_env_var(name="NEW_VAR")
    assert retrieved == "new_value", "set_env_var should allow retrieval of the new value"


def test_set_env_var_overwrite(env_behavior, monkeypatch):
    """Test that set_env_var overwrites an existing variable."""
    monkeypatch.setenv("OVERWRITE_VAR", "old")
    env_behavior.set_env_var(name="OVERWRITE_VAR", value="new")
    assert os.environ["OVERWRITE_VAR"] == "new"
    assert env_behavior.get_env_var(name="OVERWRITE_VAR") == "new"


def test_set_env_var_error_invalid_name(env_behavior):
    """Test that providing an invalid name raises a ValueError."""
    with pytest.raises(ValueError):
        env_behavior.set_env_var(name="", value="some_value")
    with pytest.raises(ValueError):
        env_behavior.set_env_var(name=None, value="some_value")


def test_get_env_var_error_invalid_name(env_behavior):
    """Test that providing an invalid name raises a ValueError."""
    with pytest.raises(ValueError):
        env_behavior.get_env_var(name="")
    with pytest.raises(ValueError):
        env_behavior.get_env_var(name=None)