# GENERATED BY METAPROGRAMMER - Safe to delete for testing
import pytest
from unittest.mock import patch, MagicMock

# Import the behavior class (adjust the import path as needed)
from docker_behavior import DockerBehavior


@pytest.fixture
def behavior():
    """Instantiate a fresh DockerBehavior for each test."""
    return DockerBehavior()


# ---------- Tests for docker_start_container ----------

def test_start_container_success(behavior):
    """Test that starting a container succeeds and returns expected data."""
    image = "nginx:latest"
    name = "test_nginx"

    # Mock the underlying tool to return a success response
    with patch.object(
        behavior,
        "docker_start_container",
        return_value={"status": "started", "image": image, "name": name},
    ) as mock_start:
        result = behavior.start_container(image=image, name=name)

        # Verify the tool was called with correct arguments
        mock_start.assert_called_once_with(image=image, name=name)

        # Assert the result matches the mocked response
        assert result["status"] == "started"
        assert result["image"] == image
        assert result["name"] == name


def test_start_container_error(behavior):
    """Test that starting a container handles errors correctly."""
    image = "nonexistent:latest"
    name = "bad_container"

    # Simulate an exception raised by the underlying tool
    with patch.object(
        behavior,
        "docker_start_container",
        side_effect=RuntimeError("Image not found"),
    ) as mock_start:
        with pytest.raises(RuntimeError, match="Image not found"):
            behavior.start_container(image=image, name=name)

        mock_start.assert_called_once_with(image=image, name=name)


# ---------- Tests for docker_stop_container ----------

def test_stop_container_success(behavior):
    """Test that stopping a container succeeds and returns expected data."""
    name = "test_nginx"

    with patch.object(
        behavior,
        "docker_stop_container",
        return_value={"status": "stopped", "name": name},
    ) as mock_stop:
        result = behavior.stop_container(name=name)

        mock_stop.assert_called_once_with(name=name)
        assert result["status"] == "stopped"
        assert result["name"] == name


def test_stop_container_error(behavior):
    """Test that stopping a container handles errors correctly."""
    name = "nonexistent_container"

    with patch.object(
        behavior,
        "docker_stop_container",
        side_effect=RuntimeError("Container not running"),
    ) as mock_stop:
        with pytest.raises(RuntimeError, match="Container not running"):
            behavior.stop_container(name=name)

        mock_stop.assert_called_once_with(name=name)


# ---------- Tests for docker_list_containers ----------

def test_list_containers_success(behavior):
    """Test that listing containers returns the expected list."""
    mock_containers = [
        {"name": "nginx", "status": "running"},
        {"name": "redis", "status": "exited"},
    ]

    with patch.object(
        behavior,
        "docker_list_containers",
        return_value=mock_containers,
    ) as mock_list:
        result = behavior.list_containers()

        mock_list.assert_called_once_with()
        assert isinstance(result, list)
        assert result == mock_containers


def test_list_containers_error(behavior):
    """Test that listing containers handles errors correctly."""
    with patch.object(
        behavior,
        "docker_list_containers",
        side_effect=RuntimeError("Docker daemon not reachable"),
    ) as mock_list:
        with pytest.raises(RuntimeError, match="Docker daemon not reachable"):
            behavior.list_containers()

        mock_list.assert_called_once_with()