# META: GENERATED_BY=MetaProgrammer
# META: GENERATOR=CreateBehaviorBehavior
# META: AUTHOR=MetaProgrammer
# META: TIMESTAMP=2025-11-07T00:59:46.034448
# META: VERSION=1.0.0
# META: PARENT_REQUEST="Provides basic arithmetic calculation tools (add, subtract, multiply, divide)"
# GENERATED BY METAPROGRAMMER - Safe to delete for testing
"""
CalculatorBehavior provides basic arithmetic tools: add and subtract.
"""

from typing import Any
from behaviors.base import AgentBehavior


class CalculatorBehavior(AgentBehavior):
    """
    Provides basic arithmetic calculation tools (add, subtract).
    """

    def __init__(self, workspace_manager=None, **kwargs):
        """
        Initialize behavior.

        Args:
            workspace_manager: Optional WorkspaceManager for file path resolution
            **kwargs: Additional parameters (ignored for extensibility)
        """
        self.workspace_manager = workspace_manager

    def get_name(self) -> str:
        """
        Return unique behavior identifier.

        This name is used for logging and identification.

        Returns:
            Behavior name string (e.g., "CalculatorBehavior")
        """
        return "CalculatorBehavior"

    def get_tools(self) -> list[dict[str, Any]]:
        """
        Return tool definitions in OpenAI function format.

        Each tool must have:
        - name: Tool identifier
        - description: What the tool does
        - parameters: JSON Schema for tool arguments

        Returns:
            List of tool definition dicts
        """
        return [
            {
                "type": "function",
                "function": {
                    "name": "add",
                    "description": "Add two numbers",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "a": {
                                "type": "number",
                                "description": "First number"
                            },
                            "b": {
                                "type": "number",
                                "description": "Second number"
                            }
                        },
                        "required": ["a", "b"]
                    }
                }
            },
            {
                "type": "function",
                "function": {
                    "name": "subtract",
                    "description": "Subtract second number from first",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "a": {
                                "type": "number",
                                "description": "First number"
                            },
                            "b": {
                                "type": "number",
                                "description": "Second number"
                            }
                        },
                        "required": ["a", "b"]
                    }
                }
            }
        ]

    def dispatch_tool(
        self,
        agent: Any,
        tool_name: str,
        args: dict[str, Any]
    ) -> dict[str, Any]:
        """
        Execute tool by name.

        Args:
            agent: Agent instance (access workspace, state, etc.)
            tool_name: Name of tool to execute
            args: Tool arguments from LLM

        Returns:
            Result dict with either:
            - {"result": value, "success": True} on success
            - {"error": message} on failure
        """
        if tool_name == "add":
            try:
                a = args.get("a")
                b = args.get("b")
                if a is None or b is None:
                    raise ValueError("Missing required arguments 'a' or 'b'")
                result = self._add(a, b)
                return {"result": result, "success": True}
            except Exception as e:
                return {"error": str(e)}

        if tool_name == "subtract":
            try:
                a = args.get("a")
                b = args.get("b")
                if a is None or b is None:
                    raise ValueError("Missing required arguments 'a' or 'b'")
                result = self._subtract(a, b)
                return {"result": result, "success": True}
            except Exception as e:
                return {"error": str(e)}

        # Not our tool, pass to parent
        return super().dispatch_tool(agent, tool_name, args)

    def _add(self, a: float, b: float) -> float:
        """
        Core addition logic.

        Args:
            a: First number
            b: Second number

        Returns:
            Sum of a and b
        """
        return a + b

    def _subtract(self, a: float, b: float) -> float:
        """
        Core subtraction logic.

        Args:
            a: First number
            b: Second number

        Returns:
            Result of a minus b
        """
        return a - b