# GENERATED BY METAPROGRAMMER - Safe to delete for testing
"""
DockerBehavior provides Docker container management with persistent state tracking.
"""

from typing import Any, Dict, List
from behaviors.base import AgentBehavior


class DockerBehavior(AgentBehavior):
    """
    Provides Docker container management with persistent state tracking.

    This behavior offers tools to start, stop, and list Docker containers,
    maintaining their state across agent sessions.
    """

    def __init__(self, workspace_manager=None, **kwargs):
        """
        Initialize behavior.

        Args:
            workspace_manager: Optional WorkspaceManager for file path resolution
            **kwargs: Additional parameters (ignored for extensibility)
        """
        self.workspace_manager = workspace_manager

    def get_name(self) -> str:
        """
        Return unique behavior identifier.

        This name is used for logging and identification.

        Returns:
            Behavior name string (e.g., "DockerBehavior")
        """
        return "DockerBehavior"

    def get_tools(self) -> List[Dict[str, Any]]:
        """
        Return tool definitions in OpenAI function format.

        Each tool must have:
        - name: Tool identifier
        - description: What the tool does
        - parameters: JSON Schema for tool arguments

        Returns:
            List of tool definition dicts
        """
        return [
            {
                "type": "function",
                "function": {
                    "name": "docker_start_container",
                    "description": "Start a Docker container and track its state",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "image": {
                                "type": "string",
                                "description": "Docker image name"
                            },
                            "name": {
                                "type": "string",
                                "description": "Container name"
                            }
                        },
                        "required": ["image", "name"]
                    }
                }
            },
            {
                "type": "function",
                "function": {
                    "name": "docker_stop_container",
                    "description": "Stop a running container and update state",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "description": "Container name to stop"
                            }
                        },
                        "required": ["name"]
                    }
                }
            },
            {
                "type": "function",
                "function": {
                    "name": "docker_list_containers",
                    "description": "List all tracked containers with their status",
                    "parameters": {
                        "type": "object",
                        "properties": {}
                    }
                }
            }
        ]

    def dispatch_tool(
        self,
        agent: Any,
        tool_name: str,
        args: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Execute tool by name.

        Args:
            agent: Agent instance (access workspace, state, etc.)
            tool_name: Name of tool to execute
            args: Tool arguments from LLM

        Returns:
            Result dict with either:
            - {"result": value, "success": True} on success
            - {"error": message} on failure
        """
        if tool_name == "docker_start_container":
            try:
                image = args.get("image")
                name = args.get("name")
                if not image or not name:
                    raise ValueError("Both 'image' and 'name' must be provided.")
                self._start_container(agent, name, image)
                return {"result": f"Container '{name}' started with image '{image}'.", "success": True}
            except Exception as e:
                return {"error": str(e)}

        if tool_name == "docker_stop_container":
            try:
                name = args.get("name")
                if not name:
                    raise ValueError("'name' must be provided.")
                self._stop_container(agent, name)
                return {"result": f"Container '{name}' stopped.", "success": True}
            except Exception as e:
                return {"error": str(e)}

        if tool_name == "docker_list_containers":
            try:
                containers = self._list_containers(agent)
                return {"result": containers, "success": True}
            except Exception as e:
                return {"error": str(e)}

        # Not our tool, pass to parent
        return super().dispatch_tool(agent, tool_name, args)

    def _start_container(self, agent: Any, name: str, image: str) -> None:
        """
        Core functionality to start a container and update state.
        """
        containers = agent.state.setdefault("docker_containers", {})
        containers[name] = {"image": image, "status": "running"}

    def _stop_container(self, agent: Any, name: str) -> None:
        """
        Core functionality to stop a container and update state.
        """
        containers = agent.state.setdefault("docker_containers", {})
        if name not in containers:
            raise ValueError(f"Container '{name}' not found.")
        containers[name]["status"] = "stopped"

    def _list_containers(self, agent: Any) -> List[Dict[str, Any]]:
        """
        Core functionality to list all tracked containers.
        """
        containers = agent.state.get("docker_containers", {})
        return [
            {"name": name, "image": info.get("image"), "status": info.get("status")}
            for name, info in containers.items()
        ]

    # OPTIONAL: Override lifecycle hooks if needed

    def on_initial_context(
        self,
        agent: Any,
        context: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        """
        Called once at agent startup.

        Use this to inject tool documentation into context.
        Standard pattern below handles tool documentation automatically.
        """
        tools = self.get_tools()
        if not tools:
            return context

        # Build tool documentation
        tool_docs = []
        for tool in tools:
            func = tool.get("function", {})
            name = func.get("name", "unknown")
            desc = func.get("description", "")
            params = func.get("parameters", {}).get("properties", {})
            required = func.get("parameters", {}).get("required", [])

            # Build parameter signature
            param_strs = []
            for param_name, param_spec in params.items():
                param_type = param_spec.get("type", "any")
                is_required = param_name in required
                if is_required:
                    param_strs.append(f"{param_name}: {param_type}")
                else:
                    param_strs.append(f"{param_name}?: {param_type}")

            param_sig = ", ".join(param_strs) if param_strs else ""
            tool_docs.append(f"  - {name}({param_sig}): {desc}")

        if tool_docs:
            tool_message = f"\n{self.get_name()} tools:\n" + "\n".join(tool_docs)
            return self.inject_user_message_after_system(context, tool_message)

        return context

    def on_goal_complete(
        self,
        agent: Any,
        goal: Dict[str, Any]
    ) -> None:
        """
        Called when a goal is completed. No special handling required for DockerBehavior.
        """
        pass