# GENERATED BY METAPROGRAMMER - Safe to delete for testing
"""
EnvironmentBehavior provides tools for managing environment variables within the agent's process.
"""

from typing import Any
import os
from behaviors.base import AgentBehavior


class EnvironmentBehavior(AgentBehavior):
    """
    Provides environment variable management tools.

    This behavior offers tools to get and set environment variables for the current process.
    """

    def __init__(self, workspace_manager=None, **kwargs):
        """
        Initialize behavior.

        Args:
            workspace_manager: Optional WorkspaceManager for file path resolution
            **kwargs: Additional parameters (ignored for extensibility)
        """
        self.workspace_manager = workspace_manager

    def get_name(self) -> str:
        """
        Return unique behavior identifier.

        Returns:
            Behavior name string (e.g., "EnvironmentBehavior")
        """
        return "EnvironmentBehavior"

    def get_tools(self) -> list[dict[str, Any]]:
        """
        Return tool definitions in OpenAI function format.

        Returns:
            List of tool definition dicts
        """
        return [
            {
                "type": "function",
                "function": {
                    "name": "get_env_var",
                    "description": "Get environment variable value with optional default",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "description": "Environment variable name"
                            },
                            "default": {
                                "type": "string",
                                "description": "Default value if variable not set"
                            }
                        },
                        "required": ["name"]
                    }
                }
            },
            {
                "type": "function",
                "function": {
                    "name": "set_env_var",
                    "description": "Set environment variable value (for current process)",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "description": "Environment variable name"
                            },
                            "value": {
                                "type": "string",
                                "description": "Value to set"
                            }
                        },
                        "required": ["name", "value"]
                    }
                }
            }
        ]

    def dispatch_tool(
        self,
        agent: Any,
        tool_name: str,
        args: dict[str, Any]
    ) -> dict[str, Any]:
        """
        Execute tool by name.

        Args:
            agent: Agent instance (access workspace, state, etc.)
            tool_name: Name of tool to execute
            args: Tool arguments from LLM

        Returns:
            Result dict with either:
            - {"result": value, "success": True} on success
            - {"error": message} on failure
        """
        if tool_name == "get_env_var":
            try:
                name = args.get("name")
                if name is None:
                    raise ValueError("Missing required argument 'name'")
                default = args.get("default")
                value = os.getenv(name, default)
                return {"result": value, "success": True}
            except Exception as e:
                return {"error": str(e)}

        if tool_name == "set_env_var":
            try:
                name = args.get("name")
                value = args.get("value")
                if name is None or value is None:
                    raise ValueError("Missing required arguments 'name' or 'value'")
                os.environ[name] = value
                return {"result": f"Set {name} to {value}", "success": True}
            except Exception as e:
                return {"error": str(e)}

        # Not our tool, pass to parent
        return super().dispatch_tool(agent, tool_name, args)

    # OPTIONAL: Override lifecycle hooks if needed

    def on_initial_context(
        self,
        agent: Any,
        context: list[dict[str, Any]]
    ) -> list[dict[str, Any]]:
        """
        Called once at agent startup.

        Use this to inject tool documentation into context.
        Standard pattern below handles tool documentation automatically.
        """
        tools = self.get_tools()
        if not tools:
            return context

        # Build tool documentation
        tool_docs = []
        for tool in tools:
            func = tool.get("function", {})
            name = func.get("name", "unknown")
            desc = func.get("description", "")
            params = func.get("parameters", {}).get("properties", {})
            required = func.get("parameters", {}).get("required", [])

            # Build parameter signature
            param_strs = []
            for param_name, param_spec in params.items():
                param_type = param_spec.get("type", "any")
                is_required = param_name in required
                if is_required:
                    param_strs.append(f"{param_name}: {param_type}")
                else:
                    param_strs.append(f"{param_name}?: {param_type}")

            param_sig = ", ".join(param_strs) if param_strs else ""
            tool_docs.append(f"  - {name}({param_sig}): {desc}")

        if tool_docs:
            tool_message = f"\n{self.get_name()} tools:\n" + "\n".join(tool_docs)
            return self.inject_user_message_after_system(context, tool_message)

        return context