# GENERATED BY METAPROGRAMMER - Safe to delete for testing

"""
GitOperationsBehavior provides Git repository management tools.
"""

from typing import Any, List, Dict
from behaviors.base import AgentBehavior
import subprocess
import os


class GitOperationsBehavior(AgentBehavior):
    """
    Provides Git repository management tools.

    This behavior provides tools for Git status, commit, and branch listing.
    """

    def __init__(self, workspace_manager=None, **kwargs):
        """
        Initialize behavior.

        Args:
            workspace_manager: Optional WorkspaceManager for file path resolution
            **kwargs: Additional parameters (ignored for extensibility)
        """
        self.workspace_manager = workspace_manager

    def get_name(self) -> str:
        """
        Return unique behavior identifier.

        This name is used for logging and identification.

        Returns:
            Behavior name string (e.g., "GitOperationsBehavior")
        """
        return "GitOperationsBehavior"

    def get_tools(self) -> List[Dict[str, Any]]:
        """
        Return tool definitions in OpenAI function format.

        Each tool must have:
        - name: Tool identifier
        - description: What the tool does
        - parameters: JSON Schema for tool arguments

        Returns:
            List of tool definition dicts
        """
        return [
            {
                "type": "function",
                "function": {
                    "name": "git_status",
                    "description": "Get Git status",
                    "parameters": {
                        "type": "object",
                        "properties": {},
                        "required": []
                    }
                }
            },
            {
                "type": "function",
                "function": {
                    "name": "git_commit",
                    "description": "Commit changes",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "message": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "message"
                        ]
                    }
                }
            },
            {
                "type": "function",
                "function": {
                    "name": "git_branch_list",
                    "description": "List branches",
                    "parameters": {
                        "type": "object",
                        "properties": {},
                        "required": []
                    }
                }
            }
        ]

    def dispatch_tool(
        self,
        agent: Any,
        tool_name: str,
        args: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Execute tool by name.

        Args:
            agent: Agent instance (access workspace, state, etc.)
            tool_name: Name of tool to execute
            args: Tool arguments from LLM

        Returns:
            Result dict with either:
            - {"result": value, "success": True} on success
            - {"error": message} on failure
        """
        if tool_name == "git_status":
            try:
                output = self._run_git_command(["status"])
                return {"result": output, "success": True}
            except Exception as e:
                return {"error": str(e)}

        if tool_name == "git_commit":
            try:
                message = args.get("message")
                if not message:
                    raise ValueError("Missing required parameter 'message'")
                output = self._run_git_command(["commit", "-m", message])
                return {"result": output, "success": True}
            except Exception as e:
                return {"error": str(e)}

        if tool_name == "git_branch_list":
            try:
                output = self._run_git_command(["branch"])
                return {"result": output, "success": True}
            except Exception as e:
                return {"error": str(e)}

        # Not our tool, pass to parent
        return super().dispatch_tool(agent, tool_name, args)

    def _run_git_command(self, args: List[str]) -> str:
        """
        Helper to run a git command in the workspace directory.

        Args:
            args: List of git command arguments

        Returns:
            Standard output of the command

        Raises:
            RuntimeError if the command fails
        """
        cwd = None
        if self.workspace_manager and hasattr(self.workspace_manager, "get_workspace_path"):
            cwd = self.workspace_manager.get_workspace_path()
        else:
            cwd = os.getcwd()

        result = subprocess.run(
            ["git"] + args,
            cwd=cwd,
            capture_output=True,
            text=True,
            check=True
        )
        return result.stdout.strip()

    # OPTIONAL: Override lifecycle hooks if needed

    def on_initial_context(
        self,
        agent: Any,
        context: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        """
        Called once at agent startup.

        Use this to inject tool documentation into context.
        Standard pattern below handles tool documentation automatically.
        """
        tools = self.get_tools()
        if not tools:
            return context

        # Build tool documentation
        tool_docs = []
        for tool in tools:
            func = tool.get("function", {})
            name = func.get("name", "unknown")
            desc = func.get("description", "")
            params = func.get("parameters", {}).get("properties", {})
            required = func.get("parameters", {}).get("required", [])

            # Build parameter signature
            param_strs = []
            for param_name, param_spec in params.items():
                param_type = param_spec.get("type", "any")
                is_required = param_name in required
                if is_required:
                    param_strs.append(f"{param_name}: {param_type}")
                else:
                    param_strs.append(f"{param_name}?: {param_type}")

            param_sig = ", ".join(param_strs) if param_strs else ""
            tool_docs.append(f"  - {name}({param_sig}): {desc}")

        if tool_docs:
            tool_message = f"\n{self.get_name()} tools:\n" + "\n".join(tool_docs)
            return self.inject_user_message_after_system(context, tool_message)

        return context

    def on_round_start(
        self,
        agent: Any,
        round_number: int
    ) -> None:
        """
        Called at the start of each round.

        Override if behavior needs to perform actions each round.
        """
        pass