# GENERATED BY METAPROGRAMMER - Safe to delete for testing
"""
HttpRequestBehavior provides tools for performing HTTP GET and POST requests.
"""

from typing import Any
import requests
from behaviors.base import AgentBehavior


class HttpRequestBehavior(AgentBehavior):
    """
    Provides HTTP GET/POST request tools for API interaction.
    """

    def __init__(self, workspace_manager=None, **kwargs):
        """
        Initialize behavior.

        Args:
            workspace_manager: Optional WorkspaceManager for file path resolution
            **kwargs: Additional parameters (ignored for extensibility)
        """
        self.workspace_manager = workspace_manager

    def get_name(self) -> str:
        """
        Return unique behavior identifier.

        This name is used for logging and identification.

        Returns:
            Behavior name string (e.g., "HttpRequestBehavior")
        """
        return "HttpRequestBehavior"

    def get_tools(self) -> list[dict[str, Any]]:
        """
        Return tool definitions in OpenAI function format.

        Each tool must have:
        - name: Tool identifier
        - description: What the tool does
        - parameters: JSON Schema for tool arguments

        Returns:
            List of tool definition dicts
        """
        return [
            {
                "type": "function",
                "function": {
                    "name": "http_get",
                    "description": "Send HTTP GET request to specified URL",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "url": {
                                "type": "string",
                                "description": "Target URL for GET request"
                            },
                            "headers": {
                                "type": "object",
                                "description": "Optional HTTP headers as key-value pairs"
                            },
                            "timeout": {
                                "type": "integer",
                                "description": "Request timeout in seconds (default: 30)"
                            }
                        },
                        "required": ["url"]
                    }
                }
            },
            {
                "type": "function",
                "function": {
                    "name": "http_post",
                    "description": "Send HTTP POST request with data to specified URL",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "url": {
                                "type": "string",
                                "description": "Target URL for POST request"
                            },
                            "data": {
                                "type": "object",
                                "description": "Data to send in POST body (will be JSON-encoded)"
                            },
                            "headers": {
                                "type": "object",
                                "description": "Optional HTTP headers as key-value pairs"
                            },
                            "timeout": {
                                "type": "integer",
                                "description": "Request timeout in seconds (default: 30)"
                            }
                        },
                        "required": ["url", "data"]
                    }
                }
            }
        ]

    def dispatch_tool(
        self,
        agent: Any,
        tool_name: str,
        args: dict[str, Any]
    ) -> dict[str, Any]:
        """
        Execute tool by name.

        Args:
            agent: Agent instance (access workspace, state, etc.)
            tool_name: Name of tool to execute
            args: Tool arguments from LLM

        Returns:
            Result dict with either:
            - {"result": value, "success": True} on success
            - {"error": message} on failure
        """
        if tool_name == "http_get":
            try:
                url = args["url"]
                headers = args.get("headers")
                timeout = args.get("timeout", 30)
                result = self._do_get(url, headers, timeout)
                return {"result": result, "success": True}
            except Exception as e:
                return {"error": str(e)}

        if tool_name == "http_post":
            try:
                url = args["url"]
                data = args["data"]
                headers = args.get("headers")
                timeout = args.get("timeout", 30)
                result = self._do_post(url, data, headers, timeout)
                return {"result": result, "success": True}
            except Exception as e:
                return {"error": str(e)}

        # Not our tool, pass to parent
        return super().dispatch_tool(agent, tool_name, args)

    def _do_get(self, url: str, headers: dict | None, timeout: int) -> str:
        """
        Perform HTTP GET request.

        Returns:
            Response text if successful.

        Raises:
            requests.exceptions.RequestException on failure.
        """
        response = requests.get(url, headers=headers, timeout=timeout)
        response.raise_for_status()
        return response.text

    def _do_post(self, url: str, data: dict, headers: dict | None, timeout: int) -> str:
        """
        Perform HTTP POST request with JSON body.

        Returns:
            Response text if successful.

        Raises:
            requests.exceptions.RequestException on failure.
        """
        response = requests.post(url, json=data, headers=headers, timeout=timeout)
        response.raise_for_status()
        return response.text

    # OPTIONAL: Override lifecycle hooks if needed

    def on_initial_context(
        self,
        agent: Any,
        context: list[dict[str, Any]]
    ) -> list[dict[str, Any]]:
        """
        Called once at agent startup.

        Use this to inject tool documentation into context.
        Standard pattern below handles tool documentation automatically.
        """
        tools = self.get_tools()
        if not tools:
            return context

        # Build tool documentation
        tool_docs = []
        for tool in tools:
            func = tool.get("function", {})
            name = func.get("name", "unknown")
            desc = func.get("description", "")
            params = func.get("parameters", {}).get("properties", {})
            required = func.get("parameters", {}).get("required", [])

            # Build parameter signature
            param_strs = []
            for param_name, param_spec in params.items():
                param_type = param_spec.get("type", "any")
                is_required = param_name in required
                if is_required:
                    param_strs.append(f"{param_name}: {param_type}")
                else:
                    param_strs.append(f"{param_name}?: {param_type}")

            param_sig = ", ".join(param_strs) if param_strs else ""
            tool_docs.append(f"  - {name}({param_sig}): {desc}")

        if tool_docs:
            tool_message = f"\n{self.get_name()} tools:\n" + "\n".join(tool_docs)
            return self.inject_user_message_after_system(context, tool_message)

        return context