# GENERATED BY METAPROGRAMMER - Safe to delete for testing
import pytest
from unittest.mock import Mock, patch

# Import the behavior class (adjust the import path as needed)
from http_request_behavior import HttpRequestBehavior


@pytest.fixture
def behavior():
    """Instantiate the HttpRequestBehavior for use in tests."""
    return HttpRequestBehavior()


def test_http_get_success(behavior, monkeypatch):
    """Test that http_get returns the expected JSON payload on a successful request."""
    # Arrange: create a mock response object
    mock_response = Mock()
    mock_response.status_code = 200
    mock_response.json.return_value = {"key": "value"}
    mock_response.raise_for_status.return_value = None

    # Patch requests.get to return the mock response
    def mock_get(url, headers=None, timeout=30):
        assert url == "https://api.example.com/data"
        assert headers == {"Authorization": "Bearer token"}
        assert timeout == 30
        return mock_response

    monkeypatch.setattr("requests.get", mock_get)

    # Act
    result = behavior.http_get(
        url="https://api.example.com/data",
        headers={"Authorization": "Bearer token"},
    )

    # Assert
    assert result == {"key": "value"}
    mock_response.raise_for_status.assert_called_once()


def test_http_get_error(behavior, monkeypatch):
    """Test that http_get propagates exceptions raised by the underlying HTTP client."""
    # Arrange: patch requests.get to raise a RequestException
    def mock_get(url, headers=None, timeout=30):
        raise requests.exceptions.RequestException("Network error")

    monkeypatch.setattr("requests.get", mock_get)

    # Act & Assert
    with pytest.raises(requests.exceptions.RequestException) as excinfo:
        behavior.http_get(url="https://api.example.com/data")

    assert "Network error" in str(excinfo.value)


def test_http_post_success(behavior, monkeypatch):
    """Test that http_post sends the correct payload and returns the expected JSON response."""
    # Arrange: create a mock response object
    mock_response = Mock()
    mock_response.status_code = 201
    mock_response.json.return_value = {"id": 123, "status": "created"}
    mock_response.raise_for_status.return_value = None

    # Patch requests.post to return the mock response
    def mock_post(url, json=None, headers=None, timeout=30):
        assert url == "https://api.example.com/create"
        assert json == {"name": "test", "value": 42}
        assert headers == {"Content-Type": "application/json"}
        assert timeout == 30
        return mock_response

    monkeypatch.setattr("requests.post", mock_post)

    # Act
    result = behavior.http_post(
        url="https://api.example.com/create",
        data={"name": "test", "value": 42},
        headers={"Content-Type": "application/json"},
    )

    # Assert
    assert result == {"id": 123, "status": "created"}
    mock_response.raise_for_status.assert_called_once()


def test_http_post_error(behavior, monkeypatch):
    """Test that http_post propagates exceptions raised by the underlying HTTP client."""
    # Arrange: patch requests.post to raise a RequestException
    def mock_post(url, json=None, headers=None, timeout=30):
        raise requests.exceptions.RequestException("Server error")

    monkeypatch.setattr("requests.post", mock_post)

    # Act & Assert
    with pytest.raises(requests.exceptions.RequestException) as excinfo:
        behavior.http_post(
            url="https://api.example.com/create",
            data={"name": "test"},
        )

    assert "Server error" in str(excinfo.value)