# META: AUTHOR=MetaProgrammer
# META: GENERATOR=CreateBehaviorBehavior
# META: TIMESTAMP=2025-11-07T01:14:04.606079
# META: PARENT_REQUEST="Dynamic tool filtering for context management - removes all tools except search_tools, then adds only relevant tools when queried"
# GENERATED BY METAPROGRAMMER - Safe to delete for testing
import pytest
from unittest.mock import patch, MagicMock

# Import the behavior class. Adjust the import path to match your project structure.
# For example, if the class is defined in `myproject.behaviors.search_tools_behavior`,
# replace the import below with the correct module path.
from search_tools_behavior import SearchToolsBehavior


# Dummy tool registry used for testing. In a real scenario this would be replaced
# by the actual tool registry used by the application.
DUMMY_TOOL_REGISTRY = [
    {"name": "search_tools", "description": "Search for tools by keyword or pattern."},
    {"name": "calculator", "description": "Performs basic arithmetic operations."},
    {"name": "weather", "description": "Provides weather forecasts for a location."},
    {"name": "translator", "description": "Translates text between languages."},
    {"name": "news_fetcher", "description": "Fetches the latest news headlines."},
    {"name": "email_sender", "description": "Sends emails via SMTP."},
]


@pytest.fixture
def behavior():
    """Instantiate the SearchToolsBehavior with a mocked tool registry."""
    # Patch the internal registry used by the behavior to our dummy registry.
    with patch.object(SearchToolsBehavior, "_tool_registry", DUMMY_TOOL_REGISTRY, create=True):
        yield SearchToolsBehavior()


def test_search_tools_success(behavior):
    """
    Test that a valid query returns the expected tools and that the context
    is updated to contain only the search_tools tool and the matching tools.
    """
    # Mock a context object that holds the current tools.
    context = MagicMock()
    context.tools = DUMMY_TOOL_REGISTRY.copy()

    # Perform the search.
    result = behavior.search_tools(query="weather", max_results=5)

    # The result should contain the matching tool(s).
    assert isinstance(result, list)
    assert len(result) == 1
    assert result[0]["name"] == "weather"

    # The context should now contain only the search_tools tool and the matched tool.
    expected_tools = [
        {"name": "search_tools", "description": "Search for tools by keyword or pattern."},
        {"name": "weather", "description": "Provides weather forecasts for a location."},
    ]
    assert context.tools == expected_tools


def test_search_tools_no_results(behavior):
    """
    Test that a query with no matching tools returns an empty list and
    the context is updated to contain only the search_tools tool.
    """
    context = MagicMock()
    context.tools = DUMMY_TOOL_REGISTRY.copy()

    result = behavior.search_tools(query="nonexistenttool", max_results=3)

    assert result == []
    expected_tools = [
        {"name": "search_tools", "description": "Search for tools by keyword or pattern."},
    ]
    assert context.tools == expected_tools


def test_search_tools_invalid_query_type(behavior):
    """
    Test that providing a non-string query raises a TypeError.
    """
    context = MagicMock()
    context.tools = DUMMY_TOOL_REGISTRY.copy()

    with pytest.raises(TypeError):
        behavior.search_tools(query=123, max_results=5)


def test_search_tools_missing_query(behavior):
    """
    Test that omitting the required query parameter raises a ValueError.
    """
    context = MagicMock()
    context.tools = DUMMY_TOOL_REGISTRY.copy()

    # Assuming the method signature requires a query argument; calling without it should raise.
    with pytest.raises(TypeError):
        behavior.search_tools(max_results=5)


def test_search_tools_max_results_limit(behavior):
    """
    Test that the max_results parameter limits the number of returned tools.
    """
    context = MagicMock()
    context.tools = DUMMY_TOOL_REGISTRY.copy()

    # Query that matches multiple tools (e.g., all tools containing 't' in the name).
    result = behavior.search_tools(query="t", max_results=2)

    # Should return at most 2 tools.
    assert len(result) <= 2
    # Ensure that the returned tools are indeed part of the registry.
    for tool in result:
        assert tool in DUMMY_TOOL_REGISTRY

    # Context should contain only the search_tools tool and the matched tools.
    expected_tools = [
        {"name": "search_tools", "description": "Search for tools by keyword or pattern."},
    ] + result
    assert context.tools == expected_tools