# GENERATED BY METAPROGRAMMER - Safe to delete for testing
import json
import pytest

from json_tools_behavior import JsonToolsBehavior


@pytest.fixture
def json_tools():
    return JsonToolsBehavior()


# ---------- parse_json ----------
def test_parse_json_success(json_tools):
    """Test that a valid JSON string is parsed into a dictionary."""
    json_str = '{"name": "Alice", "age": 30}'
    result = json_tools.parse_json(json_str)
    assert isinstance(result, dict)
    assert result == {"name": "Alice", "age": 30}


def test_parse_json_error(json_tools):
    """Test that an invalid JSON string triggers an error."""
    invalid_json = '{"name": "Alice", "age": 30'  # Missing closing brace
    try:
        result = json_tools.parse_json(invalid_json)
    except Exception as exc:
        # If the method raises an exception, ensure it's a ValueError or similar
        assert isinstance(exc, ValueError)
    else:
        # If no exception, the method should return an error dict
        assert isinstance(result, dict)
        assert "error" in result
        assert isinstance(result["error"], str)


# ---------- format_json ----------
def test_format_json_default_indent(json_tools):
    """Test formatting data with the default indentation (2 spaces)."""
    data = {"name": "Bob", "age": 25}
    formatted = json_tools.format_json(data)
    expected = json.dumps(data, indent=2)
    assert formatted == expected


def test_format_json_custom_indent(json_tools):
    """Test formatting data with a custom indentation level."""
    data = {"name": "Carol", "age": 40}
    formatted = json_tools.format_json(data, indent=4)
    expected = json.dumps(data, indent=4)
    assert formatted == expected


# ---------- validate_json_schema ----------
def test_validate_json_schema_success(json_tools):
    """Test that valid data passes schema validation."""
    data = {"name": "Dave", "age": 22}
    schema = {
        "required": ["name", "age"],
        "properties": {
            "name": {"type": "string"},
            "age": {"type": "integer"},
        },
    }
    result = json_tools.validate_json_schema(data, schema)
    # The method may return a boolean or a dict with a 'valid' key
    if isinstance(result, bool):
        assert result is True
    else:
        assert isinstance(result, dict)
        assert result.get("valid") is True


def test_validate_json_schema_missing_required(json_tools):
    """Test that missing required fields cause validation to fail."""
    data = {"name": "Eve"}  # 'age' is missing
    schema = {
        "required": ["name", "age"],
        "properties": {
            "name": {"type": "string"},
            "age": {"type": "integer"},
        },
    }
    result = json_tools.validate_json_schema(data, schema)
    if isinstance(result, bool):
        assert result is False
    else:
        assert isinstance(result, dict)
        assert result.get("valid") is False
        assert "errors" in result
        assert any("age" in err for err in result["errors"])


def test_validate_json_schema_wrong_type(json_tools):
    """Test that a field with the wrong type causes validation to fail."""
    data = {"name": "Frank", "age": "not a number"}  # age should be integer
    schema = {
        "required": ["name", "age"],
        "properties": {
            "name": {"type": "string"},
            "age": {"type": "integer"},
        },
    }
    result = json_tools.validate_json_schema(data, schema)
    if isinstance(result, bool):
        assert result is False
    else:
        assert isinstance(result, dict)
        assert result.get("valid") is False
        assert "errors" in result
        assert any("age" in err for err in result["errors"])