# GENERATED BY METAPROGRAMMER - Safe to delete for testing
import pytest
import requests
from unittest.mock import Mock, patch

# Import the behavior class (replace with the actual import path)
from your_module import HttpRequestBehavior


@pytest.fixture
def behavior():
    return HttpRequestBehavior()


def test_http_get_success(behavior, monkeypatch):
    url = "https://api.example.com/data"
    headers = {"Authorization": "Bearer token"}
    timeout = 10
    expected_json = {"key": "value"}

    # Mock the requests.get function
    mock_response = Mock()
    mock_response.status_code = 200
    mock_response.json.return_value = expected_json
    mock_response.raise_for_status = Mock()

    def mock_get(*args, **kwargs):
        assert args[0] == url
        assert kwargs.get("headers") == headers
        assert kwargs.get("timeout") == timeout
        return mock_response

    monkeypatch.setattr(requests, "get", mock_get)

    result = behavior.http_get(url, headers=headers, timeout=timeout)
    assert result == expected_json
    mock_response.raise_for_status.assert_called_once()


def test_http_get_not_found(behavior, monkeypatch):
    url = "https://api.example.com/missing"

    # Mock the requests.get function to return 404
    mock_response = Mock()
    mock_response.status_code = 404
    mock_response.raise_for_status.side_effect = requests.exceptions.HTTPError("404 Client Error")

    monkeypatch.setattr(requests, "get", lambda *_, **__: mock_response)

    with pytest.raises(requests.exceptions.HTTPError):
        behavior.http_get(url)


def test_http_get_timeout(behavior, monkeypatch):
    url = "https://api.example.com/slow"

    # Mock the requests.get function to raise a timeout
    monkeypatch.setattr(requests, "get", lambda *_, **__: (_ for _ in ()).throw(requests.exceptions.Timeout("Connection timed out")))

    with pytest.raises(requests.exceptions.Timeout):
        behavior.http_get(url)


def test_http_post_success(behavior, monkeypatch):
    url = "https://api.example.com/submit"
    data = {"name": "Alice"}
    headers = {"Content-Type": "application/json"}
    timeout = 15
    expected_json = {"status": "ok"}

    # Mock the requests.post function
    mock_response = Mock()
    mock_response.status_code = 201
    mock_response.json.return_value = expected_json
    mock_response.raise_for_status = Mock()

    def mock_post(*args, **kwargs):
        assert args[0] == url
        assert kwargs.get("json") == data
        assert kwargs.get("headers") == headers
        assert kwargs.get("timeout") == timeout
        return mock_response

    monkeypatch.setattr(requests, "post", mock_post)

    result = behavior.http_post(url, data=data, headers=headers, timeout=timeout)
    assert result == expected_json
    mock_response.raise_for_status.assert_called_once()


def test_http_post_server_error(behavior, monkeypatch):
    url = "https://api.example.com/submit"
    data = {"name": "Bob"}

    # Mock the requests.post function to return 500
    mock_response = Mock()
    mock_response.status_code = 500
    mock_response.raise_for_status.side_effect = requests.exceptions.HTTPError("500 Server Error")

    monkeypatch.setattr(requests, "post", lambda *_, **__: mock_response)

    with pytest.raises(requests.exceptions.HTTPError):
        behavior.http_post(url, data=data)


def test_http_post_timeout(behavior, monkeypatch):
    url = "https://api.example.com/submit"
    data = {"name": "Charlie"}

    # Mock the requests.post function to raise a timeout
    monkeypatch.setattr(requests, "post", lambda *_, **__: (_ for _ in ()).throw(requests.exceptions.Timeout("Connection timed out")))

    with pytest.raises(requests.exceptions.Timeout):
        behavior.http_post(url, data=data)