# GENERATED BY METAPROGRAMMER - Safe to delete for testing
import subprocess
import pytest
from subprocess import CompletedProcess, CalledProcessError

# Adjust the import path to match your project structure
# For example, if the behavior is defined in git_operations.py:
# from git_operations import GitOperationsBehavior
from git_operations_behavior import GitOperationsBehavior


@pytest.fixture
def git_behavior():
    """Create a fresh instance of GitOperationsBehavior for each test."""
    return GitOperationsBehavior()


def test_git_status_success(monkeypatch, git_behavior):
    """Test that git_status returns the expected status string on success."""
    expected_output = " M modified_file.txt\n?? untracked_file.txt\n"

    def mock_run(cmd, capture_output, text, check):
        # Verify that the correct git command is called
        assert cmd == ["git", "status", "--porcelain"]
        return CompletedProcess(args=cmd, returncode=0, stdout=expected_output, stderr="")

    monkeypatch.setattr(subprocess, "run", mock_run)

    status = git_behavior.git_status()
    assert status == expected_output


def test_git_status_error(monkeypatch, git_behavior):
    """Test that git_status propagates a CalledProcessError on failure."""
    def mock_run(cmd, capture_output, text, check):
        raise CalledProcessError(returncode=1, cmd=cmd, output="", stderr="fatal: not a git repository")

    monkeypatch.setattr(subprocess, "run", mock_run)

    with pytest.raises(CalledProcessError) as excinfo:
        git_behavior.git_status()
    assert excinfo.value.returncode == 1
    assert "not a git repository" in excinfo.value.stderr


def test_git_commit_success(monkeypatch, git_behavior):
    """Test that git_commit returns the commit hash on success."""
    commit_hash = "a1b2c3d4e5f6g7h8i9j0"
    expected_output = f" [master {commit_hash}] Commit message\n 1 file changed\n"

    def mock_run(cmd, capture_output, text, check):
        # Verify that the commit command includes the message flag
        assert cmd[:3] == ["git", "commit", "-m"]
        assert cmd[3] == "Test commit"
        return CompletedProcess(args=cmd, returncode=0, stdout=expected_output, stderr="")

    monkeypatch.setattr(subprocess, "run", mock_run)

    result = git_behavior.git_commit(message="Test commit")
    assert result == expected_output
    assert commit_hash in result


def test_git_commit_error(monkeypatch, git_behavior):
    """Test that git_commit propagates a CalledProcessError when commit fails."""
    def mock_run(cmd, capture_output, text, check):
        raise CalledProcessError(returncode=1, cmd=cmd, output="", stderr="error: pathspec 'nonexistent' did not match any file(s)")

    monkeypatch.setattr(subprocess, "run", mock_run)

    with pytest.raises(CalledProcessError) as excinfo:
        git_behavior.git_commit(message="nonexistent")
    assert excinfo.value.returncode == 1
    assert "did not match" in excinfo.value.stderr


def test_git_branch_list_success(monkeypatch, git_behavior):
    """Test that git_branch_list returns a list of branch names on success."""
    branch_output = "  main\n* feature-branch\n  bugfix\n"
    expected_branches = ["main", "feature-branch", "bugfix"]

    def mock_run(cmd, capture_output, text, check):
        assert cmd == ["git", "branch"]
        return CompletedProcess(args=cmd, returncode=0, stdout=branch_output, stderr="")

    monkeypatch.setattr(subprocess, "run", mock_run)

    branches = git_behavior.git_branch_list()
    assert branches == expected_branches


def test_git_branch_list_error(monkeypatch, git_behavior):
    """Test that git_branch_list propagates a CalledProcessError when listing fails."""
    def mock_run(cmd, capture_output, text, check):
        raise CalledProcessError(returncode=128, cmd=cmd, output="", stderr="fatal: not a git repository (or any of the parent directories): .git")

    monkeypatch.setattr(subprocess, "run", mock_run)

    with pytest.raises(CalledProcessError) as excinfo:
        git_behavior.git_branch_list()
    assert excinfo.value.returncode == 128
    assert "not a git repository" in excinfo.value.stderr