# GENERATED BY METAPROGRAMMER - Safe to delete for testing
import pytest
from unittest.mock import Mock, patch

# Adjust the import path to match your project structure
# Replace `your_module` with the actual module name where HttpRequestBehavior is defined
from your_module import HttpRequestBehavior


@pytest.fixture
def behavior():
    return HttpRequestBehavior()


def test_http_get_success(behavior):
    """Test that http_get returns the JSON payload on a successful GET request."""
    mock_response = Mock()
    mock_response.status_code = 200
    mock_response.json.return_value = {"key": "value"}

    with patch("requests.get", return_value=mock_response) as mock_get:
        result = behavior.http_get(
            url="https://api.example.com/resource",
            headers={"Authorization": "Bearer token"},
            timeout=10,
        )

        # Verify that requests.get was called with the correct parameters
        mock_get.assert_called_once_with(
            "https://api.example.com/resource",
            headers={"Authorization": "Bearer token"},
            timeout=10,
        )

        # Verify the behavior returns the JSON payload
        assert result == {"key": "value"}


def test_http_get_error(behavior):
    """Test that http_get propagates exceptions raised by requests."""
    with patch("requests.get", side_effect=requests.exceptions.Timeout):
        with pytest.raises(requests.exceptions.Timeout):
            behavior.http_get(url="https://api.example.com/resource")


def test_http_post_success(behavior):
    """Test that http_post returns the JSON payload on a successful POST request."""
    mock_response = Mock()
    mock_response.status_code = 201
    mock_response.json.return_value = {"id": 123, "status": "created"}

    with patch("requests.post", return_value=mock_response) as mock_post:
        payload = {"name": "test"}
        result = behavior.http_post(
            url="https://api.example.com/resource",
            data=payload,
            headers={"Content-Type": "application/json"},
            timeout=15,
        )

        # Verify that requests.post was called with the correct parameters
        mock_post.assert_called_once_with(
            "https://api.example.com/resource",
            json=payload,
            headers={"Content-Type": "application/json"},
            timeout=15,
        )

        # Verify the behavior returns the JSON payload
        assert result == {"id": 123, "status": "created"}


def test_http_post_error(behavior):
    """Test that http_post propagates exceptions raised by requests."""
    with patch("requests.post", side_effect=requests.exceptions.ConnectionError):
        with pytest.raises(requests.exceptions.ConnectionError):
            behavior.http_post(
                url="https://api.example.com/resource",
                data={"name": "test"},
            )