# GENERATED BY METAPROGRAMMER - Safe to delete for testing
import pytest
from unittest.mock import MagicMock, patch

# Import the behavior class (adjust the import path as needed)
try:
    from docker_behavior import DockerBehavior
except ImportError:
    # If the module name differs, adjust accordingly
    from behaviors.docker_behavior import DockerBehavior

# Import docker for exception classes
import docker


@pytest.fixture
def mock_docker_client():
    """
    Fixture that patches docker.from_env to return a mock client with
    containers attribute containing run, get, and list methods.
    """
    mock_client = MagicMock()
    mock_containers = MagicMock()
    mock_client.containers = mock_containers
    with patch("docker.from_env", return_value=mock_client):
        yield mock_client


def test_docker_start_container_success(mock_docker_client):
    """
    Test that DockerBehavior.docker_start_container starts a container
    and returns the expected result when the Docker API call succeeds.
    """
    # Arrange
    behavior = DockerBehavior()
    image = "nginx:latest"
    name = "test_container"

    # Mock the container returned by the Docker client
    mock_container = MagicMock()
    mock_container.attrs = {"Name": name, "State": {"Status": "running"}}
    mock_docker_client.containers.run.return_value = mock_container

    # Act
    result = behavior.docker_start_container(image=image, name=name)

    # Assert
    mock_docker_client.containers.run.assert_called_once_with(
        image, name=name, detach=True
    )
    assert isinstance(result, dict)
    assert result.get("name") == name
    assert result.get("status") == "running"


def test_docker_start_container_error(mock_docker_client):
    """
    Test that DockerBehavior.docker_start_container propagates an exception
    when the Docker API call fails.
    """
    # Arrange
    behavior = DockerBehavior()
    image = "nginx:latest"
    name = "test_container"

    # Configure the mock to raise an APIError
    mock_docker_client.containers.run.side_effect = docker.errors.APIError("Start failed")

    # Act & Assert
    with pytest.raises(docker.errors.APIError):
        behavior.docker_start_container(image=image, name=name)


def test_docker_stop_container_success(mock_docker_client):
    """
    Test that DockerBehavior.docker_stop_container stops a running container
    and returns the expected result when the Docker API call succeeds.
    """
    # Arrange
    behavior = DockerBehavior()
    name = "test_container"

    # Mock the container returned by get
    mock_container = MagicMock()
    mock_docker_client.containers.get.return_value = mock_container

    # Act
    result = behavior.docker_stop_container(name=name)

    # Assert
    mock_docker_client.containers.get.assert_called_once_with(name)
    mock_container.stop.assert_called_once()
    assert isinstance(result, dict)
    assert result.get("name") == name
    assert result.get("status") == "stopped"


def test_docker_stop_container_error(mock_docker_client):
    """
    Test that DockerBehavior.docker_stop_container propagates an exception
    when the Docker API call fails.
    """
    # Arrange
    behavior = DockerBehavior()
    name = "test_container"

    # Configure the mock to raise an APIError when getting the container
    mock_docker_client.containers.get.side_effect = docker.errors.APIError("Stop failed")

    # Act & Assert
    with pytest.raises(docker.errors.APIError):
        behavior.docker_stop_container(name=name)


def test_docker_list_containers_success(mock_docker_client):
    """
    Test that DockerBehavior.docker_list_containers returns a list of
    container status dictionaries when the Docker API call succeeds.
    """
    # Arrange
    behavior = DockerBehavior()

    # Create mock containers
    mock_container1 = MagicMock()
    mock_container1.attrs = {"Name": "c1", "State": {"Status": "running"}}
    mock_container2 = MagicMock()
    mock_container2.attrs = {"Name": "c2", "State": {"Status": "exited"}}

    mock_docker_client.containers.list.return_value = [mock_container1, mock_container2]

    # Act
    result = behavior.docker_list_containers()

    # Assert
    mock_docker_client.containers.list.assert_called_once_with(all=True)
    assert isinstance(result, list)
    assert len(result) == 2
    assert result[0]["name"] == "c1"
    assert result[0]["status"] == "running"
    assert result[1]["name"] == "c2"
    assert result[1]["status"] == "exited"


def test_docker_list_containers_error(mock_docker_client):
    """
    Test that DockerBehavior.docker_list_containers propagates an exception
    when the Docker API call fails.
    """
    # Arrange
    behavior = DockerBehavior()

    # Configure the mock to raise an APIError
    mock_docker_client.containers.list.side_effect = docker.errors.APIError("List failed")

    # Act & Assert
    with pytest.raises(docker.errors.APIError):
        behavior.docker_list_containers()