"""
LLM summarization utilities for Jetbox agents.

Provides reusable LLM summarization functions with consistent error handling.
"""

from typing import Any


def summarize_with_llm(
    prompt: str,
    model: str = "gpt-oss:20b",
    temperature: float = 0.2,
    inactivity_timeout: int = 30,
    max_total_time: int = 60,
) -> str:
    """
    Use LLM to generate a summary based on the provided prompt.

    This is a convenience wrapper around chat_with_inactivity_timeout
    for the common pattern of asking an LLM to summarize something.

    Args:
        prompt: The summarization prompt (should include content to summarize)
        model: Model name (default: gpt-oss:20b)
        temperature: Temperature for sampling (default: 0.2 for factual summaries)
        inactivity_timeout: Max seconds without activity (default: 30s)
        max_total_time: Max total generation time (default: 60s)

    Returns:
        Summary text generated by LLM

    Raises:
        Exception: If LLM call fails (caller should handle)
    """
    from llm_utils import chat_with_inactivity_timeout

    response = chat_with_inactivity_timeout(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        options={"temperature": temperature},
        inactivity_timeout=inactivity_timeout,
        max_total_time=max_total_time,
    )

    return response.get("message", {}).get("content", "")


def summarize_messages(
    messages: list[dict[str, Any]],
    model: str = "gpt-oss:20b",
    temperature: float = 0.2,
) -> str:
    """
    Summarize a sequence of agent messages (conversation history).

    Args:
        messages: List of message dicts to summarize
        model: Model name (default: gpt-oss:20b)
        temperature: Temperature for sampling (default: 0.2)

    Returns:
        Concise summary of the messages

    Raises:
        Exception: If summarization fails (caller should handle)
    """
    # Build a prompt asking for summary - aggressively truncate for compactness
    messages_text = []
    for msg in messages:
        role = msg.get("role", "unknown")
        content = str(msg.get("content", ""))
        tool_calls = msg.get("tool_calls")

        if tool_calls:
            # Just show tool names, not full arguments
            tool_names = str(tool_calls)[:200]
            messages_text.append(f"[{role}] {tool_names}")
        elif content:
            # Aggressively truncate - we only need gist for summarization
            if role == "tool":
                # Tool results: just first 100 chars (usually enough to see success/error)
                content = content[:100] + ("..." if len(content) > 100 else "")
            else:
                # Other messages: first 300 chars
                content = content[:300] + ("..." if len(content) > 300 else "")
            messages_text.append(f"[{role}] {content}")

    prompt = f"""Provide an extremely concise summary (max 200 words) of this conversation, focusing ONLY on:
1. Files created/modified (just names, not content)
2. Commands run (results only if they failed)
3. Current state/progress

Omit: successful tool outputs, file contents, verbose explanations.
Format: Dense bullet points.

Conversation:
{chr(10).join(messages_text)}

Concise summary (max 200 words):"""

    return summarize_with_llm(
        prompt=prompt,
        model=model,
        temperature=temperature,
        inactivity_timeout=30,
        max_total_time=60,
    )
