#!/usr/bin/env python3
"""Cleanup script for MetaProgrammer generated files."""

from pathlib import Path
import shutil

MARKER = "GENERATED BY METAPROGRAMMER"

# Core behavior files that should NEVER be deleted (even if they contain the marker)
CORE_BEHAVIORS = {
    "create_behavior.py",
    "create_agent.py",
    "validation.py",
    "sandbox_test.py",
    "__init__.py",
    "base.py"
}

def cleanup_generated_files():
    """Remove all files marked with generation marker."""
    print("=" * 60)
    print("Cleaning up MetaProgrammer generated files")
    print("=" * 60)
    print()

    # Collect files to remove
    behaviors_to_remove = []
    tests_to_remove = []
    agents_to_remove = []

    # Find generated behaviors
    behaviors_dir = Path("behaviors")
    if behaviors_dir.exists():
        for file in behaviors_dir.glob("*.py"):
            # Skip core behavior files
            if file.name in CORE_BEHAVIORS:
                continue
            try:
                if MARKER in file.read_text():
                    behaviors_to_remove.append(file)
            except Exception:
                pass

    # Find generated tests
    tests_dir = Path("tests")
    if tests_dir.exists():
        for file in tests_dir.glob("test_*.py"):
            try:
                if MARKER in file.read_text():
                    tests_to_remove.append(file)
            except Exception:
                pass

    # Find generated agent configs
    agents_dir = Path("config/agents")
    if agents_dir.exists():
        for file in agents_dir.glob("*.yaml"):
            try:
                if MARKER in file.read_text():
                    agents_to_remove.append(file)
            except Exception:
                pass

    # Report counts
    print(f"Found:")
    print(f"  - {len(behaviors_to_remove)} generated behaviors")
    print(f"  - {len(tests_to_remove)} generated tests")
    print(f"  - {len(agents_to_remove)} generated agent configs")
    print()

    # Remove behaviors
    if behaviors_to_remove:
        print("Removing generated behaviors:")
        for file in behaviors_to_remove:
            print(f"  - {file}")
            file.unlink()

    # Remove tests
    if tests_to_remove:
        print()
        print("Removing generated tests:")
        for file in tests_to_remove:
            print(f"  - {file}")
            file.unlink()

    # Remove agent configs
    if agents_to_remove:
        print()
        print("Removing generated agent configs:")
        for file in agents_to_remove:
            print(f"  - {file}")
            file.unlink()

    # Clean up test workspaces
    print()
    print("Cleaning test workspaces:")
    workspace_dir = Path(".agent_workspace")
    if workspace_dir.exists():
        count = 0
        for test_workspace in workspace_dir.glob("meta_test_*"):
            if test_workspace.is_dir():
                shutil.rmtree(test_workspace)
                count += 1
        print(f"  - Removed {count} test workspace directories")

    print()
    print("=" * 60)
    print("Cleanup complete!")
    print("=" * 60)

if __name__ == "__main__":
    cleanup_generated_files()
