#!/bin/bash
# Cleanup script for MetaProgrammer generated files
# Removes all files marked with "GENERATED BY METAPROGRAMMER"

echo "============================================================"
echo "Cleaning up MetaProgrammer generated files"
echo "============================================================"

# Count files before cleanup
behavior_count=$(grep -l "GENERATED BY METAPROGRAMMER" behaviors/*.py 2>/dev/null | wc -l)
test_count=$(grep -l "GENERATED BY METAPROGRAMMER" tests/test_*.py 2>/dev/null | wc -l)
agent_count=$(grep -l "GENERATED BY METAPROGRAMMER" config/agents/*.yaml 2>/dev/null | wc -l)

echo ""
echo "Found:"
echo "  - $behavior_count generated behaviors"
echo "  - $test_count generated tests"
echo "  - $agent_count generated agent configs"
echo ""

# Remove generated behaviors
if [ "$behavior_count" -gt 0 ]; then
    echo "Removing generated behaviors:"
    grep -l "GENERATED BY METAPROGRAMMER" behaviors/*.py 2>/dev/null | while read file; do
        echo "  - $file"
        rm -f "$file"
    done
fi

# Remove generated tests
if [ "$test_count" -gt 0 ]; then
    echo ""
    echo "Removing generated tests:"
    grep -l "GENERATED BY METAPROGRAMMER" tests/test_*.py 2>/dev/null | while read file; do
        echo "  - $file"
        rm -f "$file"
    done
fi

# Remove generated agent configs
if [ "$agent_count" -gt 0 ]; then
    echo ""
    echo "Removing generated agent configs:"
    grep -l "GENERATED BY METAPROGRAMMER" config/agents/*.yaml 2>/dev/null | while read file; do
        echo "  - $file"
        rm -f "$file"
    done
fi

# Clean up test workspaces
echo ""
echo "Cleaning test workspaces:"
rm -rf .agent_workspace/meta_test_* 2>/dev/null
echo "  - Removed .agent_workspace/meta_test_* directories"

echo ""
echo "============================================================"
echo "Cleanup complete!"
echo "============================================================"
