name: hrm-jepa
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.11

  # PyTorch with CUDA support (RTX 3090 - CUDA 12.x)
  - pytorch=2.3.*
  - torchvision=0.18.*
  - pytorch-cuda=12.1

  # Core scientific computing
  - numpy>=1.26.0
  - pillow>=10.0.0
  - pyyaml>=6.0
  - tqdm>=4.66.0

  # Web framework & UI
  - fastapi>=0.110.0
  - uvicorn>=0.28.0

  # Development tools
  - pytest>=8.0.0
  - pytest-cov>=4.1.0
  - ruff>=0.3.0
  - black>=24.0.0
  - mypy>=1.9.0
  - pre-commit>=3.6.0

  # Pip packages not in conda
  - pip
  - pip:
    - gradio>=4.0.0

# Platform-specific notes for Windows + RTX 3090:
# - Ensure CUDA 12.1 drivers are installed
# - RTX 3090 has 24GB VRAM, compute capability 8.6
# - Use torch.backends.cudnn.deterministic = True for reproducibility
# - Consider bf16 for memory efficiency
