# GENERATED BY METAPROGRAMMER - Safe to delete for testing
"""
DockerBehavior provides Docker container management with persistent state tracking.
"""

from typing import Any
import json
import os
import uuid
import subprocess
from behaviors.base import AgentBehavior
from behaviors.rule_of_two_types import RuleOfTwoProperty


class DockerBehavior(AgentBehavior):
    """
    Provides Docker container management with persistent state tracking.

    This behavior offers tools to start, stop, and list Docker containers,
    maintaining an internal state of container IDs and statuses across agent runs.

    Security: [B] SENSITIVE_ACCESS only
    - Runs Docker containers with filesystem access
    - Does not push to network on its own (containers might, but behavior doesn't)
    """

    # Rule of Two: [B] only - Docker containers have filesystem access
    rule_of_two_properties = {RuleOfTwoProperty.SENSITIVE_ACCESS}

    def __init__(self, workspace_manager=None, **kwargs):
        """
        Initialize behavior.

        Args:
            workspace_manager: Optional WorkspaceManager for file path resolution
            **kwargs: Additional parameters (ignored for extensibility)
        """
        self.workspace_manager = workspace_manager
        self.containers = {}  # key: container name, value: dict with id and status
        self.state_file = os.path.join(
            self.workspace_manager.get_workspace_path() if self.workspace_manager else ".",
            "docker_state.json",
        )

    def get_name(self) -> str:
        """
        Return unique behavior identifier.

        This name is used for logging and identification.

        Returns:
            Behavior name string (e.g., "DockerBehavior")
        """
        return "DockerBehavior"

    def get_tools(self) -> list[dict[str, Any]]:
        """
        Return tool definitions in OpenAI function format.

        Each tool must have:
        - name: Tool identifier
        - description: What the tool does
        - parameters: JSON Schema for tool arguments

        Returns:
            List of tool definition dicts
        """
        return [
            {
                "type": "function",
                "function": {
                    "name": "docker_start_container",
                    "description": "Start a Docker container and track its state",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "image": {
                                "type": "string",
                                "description": "Docker image name",
                            },
                            "name": {
                                "type": "string",
                                "description": "Container name",
                            },
                        },
                        "required": ["image", "name"],
                    },
                },
            },
            {
                "type": "function",
                "function": {
                    "name": "docker_stop_container",
                    "description": "Stop a running container and update state",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "description": "Container name to stop",
                            },
                        },
                        "required": ["name"],
                    },
                },
            },
            {
                "type": "function",
                "function": {
                    "name": "docker_list_containers",
                    "description": "List all tracked containers with their status",
                    "parameters": {
                        "type": "object",
                        "properties": {},
                        "required": [],
                    },
                },
            },
        ]

    def dispatch_tool(
        self,
        agent: Any,
        tool_name: str,
        args: dict[str, Any]
    ) -> dict[str, Any]:
        """
        Execute tool by name.

        Args:
            agent: Agent instance (access workspace, state, etc.)
            tool_name: Name of tool to execute
            args: Tool arguments from LLM

        Returns:
            Result dict with either:
            - {"result": value, "success": True} on success
            - {"error": message} on failure
        """
        if tool_name == "docker_start_container":
            try:
                image = args.get("image")
                name = args.get("name")
                if not image or not name:
                    raise ValueError("Both 'image' and 'name' are required.")
                container_id = self._do_start_container(image, name)
                return {"result": {"container_id": container_id}, "success": True}
            except Exception as e:
                return {"error": str(e)}

        if tool_name == "docker_stop_container":
            try:
                name = args.get("name")
                if not name:
                    raise ValueError("'name' is required.")
                self._do_stop_container(name)
                return {"result": f"Container '{name}' stopped.", "success": True}
            except Exception as e:
                return {"error": str(e)}

        if tool_name == "docker_list_containers":
            try:
                containers = self._do_list_containers()
                return {"result": containers, "success": True}
            except Exception as e:
                return {"error": str(e)}

        # Not our tool, pass to parent
        return super().dispatch_tool(agent, tool_name, args)

    def _do_start_container(self, image: str, name: str) -> str:
        """
        Start a Docker container and update internal state.

        Returns the container ID.
        """
        # Run docker to start container
        cmd = ["docker", "run", "-d", "--name", name, image]
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        container_id = result.stdout.strip()
        self.containers[name] = {"id": container_id, "status": "running"}
        return container_id

    def _do_stop_container(self, name: str) -> None:
        """
        Stop a running Docker container and update internal state.
        """
        if name not in self.containers:
            raise ValueError(f"Container '{name}' not tracked.")
        cmd = ["docker", "stop", name]
        subprocess.run(cmd, capture_output=True, text=True, check=True)
        self.containers[name]["status"] = "stopped"

    def _do_list_containers(self) -> list[dict[str, Any]]:
        """
        Return list of tracked containers with their status.
        """
        return [
            {"name": name, "id": info["id"], "status": info["status"]}
            for name, info in self.containers.items()
        ]

    def _load_state(self) -> None:
        """
        Load container state from persistent storage.
        """
        if os.path.exists(self.state_file):
            try:
                with open(self.state_file, "r", encoding="utf-8") as f:
                    self.containers = json.load(f)
            except Exception:
                self.containers = {}
        else:
            self.containers = {}

    def _save_state(self) -> None:
        """
        Save container state to persistent storage.
        """
        try:
            with open(self.state_file, "w", encoding="utf-8") as f:
                json.dump(self.containers, f, indent=2)
        except Exception:
            pass

    def on_initial_context(
        self,
        agent: Any,
        context: list[dict[str, Any]]
    ) -> list[dict[str, Any]]:
        """
        Called once at agent startup.

        Use this to inject tool documentation into context.
        Standard pattern below handles tool documentation automatically.
        """
        self._load_state()
        return super().on_initial_context(agent, context)

    def on_goal_complete(
        self,
        agent: Any,
        context: list[dict[str, Any]]
    ) -> list[dict[str, Any]]:
        """
        Called when a goal is completed.

        Persist the container state.
        """
        self._save_state()
        return super().on_goal_complete(agent, context)