# GENERATED BY METAPROGRAMMER - Safe to delete for testing
"""
EnvironmentBehavior provides tools to get and set environment variables.
"""

from typing import Any
import os
from behaviors.base import AgentBehavior
from behaviors.rule_of_two_types import RuleOfTwoProperty


class EnvironmentBehavior(AgentBehavior):
    """
    Provides environment variable management tools.

    This behavior provides tools for getting and setting environment variables
    within the current process.

    Security: DYNAMIC based on workspace characteristics
    - [B] SENSITIVE_ACCESS: Only if workspace has sensitive info (env vars can contain API keys, tokens)
    - [] None: If workspace has no sensitive info (e.g., Jetbox repo)
    """

    # Rule of Two: Empty static fallback (dynamically computed at runtime)
    rule_of_two_properties = set()

    def __init__(self, workspace_manager=None, **kwargs):
        """
        Initialize behavior.

        Args:
            workspace_manager: Optional WorkspaceManager for file path resolution
            **kwargs: Additional parameters (ignored for extensibility)
        """
        self.workspace_manager = workspace_manager

    def get_name(self) -> str:
        """
        Return unique behavior identifier.

        This name is used for logging and identification.

        Returns:
            Behavior name string (e.g., "EnvironmentBehavior")
        """
        return "EnvironmentBehavior"

    def get_rule_of_two_properties(self, agent, security_context):
        """
        Get Rule of Two properties (context-aware).

        Dynamic behavior based on workspace characteristics:
        - [B] SENSITIVE_ACCESS: Only if workspace has sensitive files (env vars can contain API keys)
        - [] None: If workspace has no sensitive files

        Args:
            agent: Agent instance
            security_context: SecurityContext with workspace characteristics

        Returns:
            Set of properties for current context ([] or [B])
        """
        props = set()

        # [B] SENSITIVE_ACCESS - only if workspace contains sensitive files
        if security_context and security_context.workspace_has_sensitive_files:
            props.add(RuleOfTwoProperty.SENSITIVE_ACCESS)

        return props

    def get_tools(self) -> list[dict[str, Any]]:
        """
        Return tool definitions in OpenAI function format.

        Each tool must have:
        - name: Tool identifier
        - description: What the tool does
        - parameters: JSON Schema for tool arguments

        Returns:
            List of tool definition dicts
        """
        return [
            {
                "type": "function",
                "function": {
                    "name": "get_env_var",
                    "description": "Get environment variable value with optional default",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "description": "Environment variable name"
                            },
                            "default": {
                                "type": "string",
                                "description": "Default value if variable not set"
                            }
                        },
                        "required": ["name"]
                    }
                }
            },
            {
                "type": "function",
                "function": {
                    "name": "set_env_var",
                    "description": "Set environment variable value (for current process)",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "description": "Environment variable name"
                            },
                            "value": {
                                "type": "string",
                                "description": "Value to set"
                            }
                        },
                        "required": ["name", "value"]
                    }
                }
            }
        ]

    def dispatch_tool(
        self,
        agent: Any,
        tool_name: str,
        args: dict[str, Any]
    ) -> dict[str, Any]:
        """
        Execute tool by name.

        Args:
            agent: Agent instance (access workspace, state, etc.)
            tool_name: Name of tool to execute
            args: Tool arguments from LLM

        Returns:
            Result dict with either:
            - {"result": value, "success": True} on success
            - {"error": message} on failure
        """
        if tool_name == "get_env_var":
            try:
                name = args.get("name")
                if name is None:
                    return {"error": "Missing required parameter 'name'"}
                default = args.get("default")
                value = os.getenv(name, default)
                return {"result": value, "success": True}
            except Exception as e:
                return {"error": str(e)}

        if tool_name == "set_env_var":
            try:
                name = args.get("name")
                value = args.get("value")
                if name is None or value is None:
                    return {"error": "Missing required parameters 'name' or 'value'"}
                os.environ[name] = value
                return {"result": f"Set {name} to {value}", "success": True}
            except Exception as e:
                return {"error": str(e)}

        return super().dispatch_tool(agent, tool_name, args)

    def on_initial_context(
        self,
        agent: Any,
        context: list[dict[str, Any]]
    ) -> list[dict[str, Any]]:
        """
        Called once at agent startup.

        Use this to inject tool documentation into context.
        Standard pattern below handles tool documentation automatically.
        """
        tools = self.get_tools()
        if not tools:
            return context

        tool_docs = []
        for tool in tools:
            func = tool.get("function", {})
            name = func.get("name", "unknown")
            desc = func.get("description", "")
            params = func.get("parameters", {}).get("properties", {})
            required = func.get("parameters", {}).get("required", [])

            param_strs = []
            for param_name, param_spec in params.items():
                param_type = param_spec.get("type", "any")
                is_required = param_name in required
                if is_required:
                    param_strs.append(f"{param_name}: {param_type}")
                else:
                    param_strs.append(f"{param_name}?: {param_type}")

            param_sig = ", ".join(param_strs) if param_strs else ""
            tool_docs.append(f"  - {name}({param_sig}): {desc}")

        if tool_docs:
            tool_message = f"\n{self.get_name()} tools:\n" + "\n".join(tool_docs)
            return self.inject_user_message_after_system(context, tool_message)

        return context