# GENERATED BY METAPROGRAMMER - Safe to delete for testing
"""
JsonToolsBehavior provides JSON manipulation tools for parsing, formatting, and validation.
"""

from typing import Any, Dict, List
import json
from behaviors.base import AgentBehavior


class JsonToolsBehavior(AgentBehavior):
    """
    Provides JSON manipulation tools for parsing, formatting, and validation.
    """

    def __init__(self, workspace_manager=None, **kwargs):
        """
        Initialize behavior.

        Args:
            workspace_manager: Optional WorkspaceManager for file path resolution
            **kwargs: Additional parameters (ignored for extensibility)
        """
        self.workspace_manager = workspace_manager

    def get_name(self) -> str:
        """
        Return unique behavior identifier.

        This name is used for logging and identification.

        Returns:
            Behavior name string (e.g., "JsonToolsBehavior")
        """
        return "JsonToolsBehavior"

    def get_tools(self) -> list[dict[str, Any]]:
        """
        Return tool definitions in OpenAI function format.

        Each tool must have:
        - name: Tool identifier
        - description: What the tool does
        - parameters: JSON Schema for tool arguments

        Returns:
            List of tool definition dicts
        """
        return [
            {
                "type": "function",
                "function": {
                    "name": "parse_json",
                    "description": "Parse JSON string to dictionary. Returns error dict if parsing fails.",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "json_string": {
                                "type": "string",
                                "description": "JSON string to parse"
                            }
                        },
                        "required": ["json_string"]
                    }
                }
            },
            {
                "type": "function",
                "function": {
                    "name": "format_json",
                    "description": "Format data as JSON string with optional indentation",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "data": {
                                "type": "object",
                                "description": "Data to format as JSON"
                            },
                            "indent": {
                                "type": "integer",
                                "description": "Indentation spaces (default: 2)"
                            }
                        },
                        "required": ["data"]
                    }
                }
            },
            {
                "type": "function",
                "function": {
                    "name": "validate_json_schema",
                    "description": "Validate data against JSON schema (basic validation)",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "data": {
                                "type": "object",
                                "description": "Data to validate"
                            },
                            "schema": {
                                "type": "object",
                                "description": "JSON schema definition (required/properties)"
                            }
                        },
                        "required": ["data", "schema"]
                    }
                }
            }
        ]

    def dispatch_tool(
        self,
        agent: Any,
        tool_name: str,
        args: dict[str, Any]
    ) -> dict[str, Any]:
        """
        Execute tool by name.

        Args:
            agent: Agent instance (access workspace, state, etc.)
            tool_name: Name of tool to execute
            args: Tool arguments from LLM

        Returns:
            Result dict with either:
            - {"result": value, "success": True} on success
            - {"error": message} on failure
        """
        if tool_name == "parse_json":
            try:
                json_string = args.get("json_string")
                if json_string is None:
                    raise ValueError("Missing 'json_string' argument")
                parsed = json.loads(json_string)
                return {"result": parsed, "success": True}
            except json.JSONDecodeError as e:
                return {"error": f"JSON decode error: {str(e)}"}
            except Exception as e:
                return {"error": str(e)}

        if tool_name == "format_json":
            try:
                data = args.get("data")
                if data is None:
                    raise ValueError("Missing 'data' argument")
                indent = args.get("indent", 2)
                if not isinstance(indent, int):
                    raise ValueError("'indent' must be an integer")
                formatted = json.dumps(data, indent=indent)
                return {"result": formatted, "success": True}
            except Exception as e:
                return {"error": str(e)}

        if tool_name == "validate_json_schema":
            try:
                data = args.get("data")
                schema = args.get("schema")
                if data is None or schema is None:
                    raise ValueError("Missing 'data' or 'schema' argument")
                errors = self._validate_schema(data, schema)
                valid = len(errors) == 0
                return {"result": {"valid": valid, "errors": errors}, "success": True}
            except Exception as e:
                return {"error": str(e)}

        # Not our tool, pass to parent
        return super().dispatch_tool(agent, tool_name, args)

    def _validate_schema(self, data: Any, schema: Dict[str, Any]) -> List[str]:
        """
        Basic JSON schema validation.

        Supports 'required' and 'properties' with type checking.
        """
        errors: List[str] = []

        required = schema.get("required", [])
        properties = schema.get("properties", {})

        # Check required fields
        for key in required:
            if key not in data:
                errors.append(f"Missing required field: {key}")

        # Type mapping
        type_map = {
            "string": str,
            "integer": int,
            "number": (int, float),
            "boolean": bool,
            "object": dict,
            "array": list
        }

        # Check property types
        for key, prop in properties.items():
            if key in data:
                expected_type = prop.get("type")
                if expected_type:
                    py_type = type_map.get(expected_type)
                    if py_type and not isinstance(data[key], py_type):
                        errors.append(
                            f"Field '{key}' expected type '{expected_type}', got '{type(data[key]).__name__}'"
                        )

        return errors

    # OPTIONAL: Override lifecycle hooks if needed

    def on_initial_context(
        self,
        agent: Any,
        context: list[dict[str, Any]]
    ) -> list[dict[str, Any]]:
        """
        Called once at agent startup.

        Use this to inject tool documentation into context.
        Standard pattern below handles tool documentation automatically.
        """
        tools = self.get_tools()
        if not tools:
            return context

        # Build tool documentation
        tool_docs = []
        for tool in tools:
            func = tool.get("function", {})
            name = func.get("name", "unknown")
            desc = func.get("description", "")
            params = func.get("parameters", {}).get("properties", {})
            required = func.get("parameters", {}).get("required", [])

            # Build parameter signature
            param_strs = []
            for param_name, param_spec in params.items():
                param_type = param_spec.get("type", "any")
                is_required = param_name in required
                if is_required:
                    param_strs.append(f"{param_name}: {param_type}")
                else:
                    param_strs.append(f"{param_name}?: {param_type}")

            param_sig = ", ".join(param_strs) if param_strs else ""
            tool_docs.append(f"  - {name}({param_sig}): {desc}")

        if tool_docs:
            tool_message = f"\n{self.get_name()} tools:\n" + "\n".join(tool_docs)
            return self.inject_user_message_after_system(context, tool_message)

        return context