# META: AUTHOR=MetaProgrammer
# META: GENERATOR=CreateBehaviorBehavior
# META: TIMESTAMP=2025-11-07T01:14:04.606079
# META: PARENT_REQUEST="Dynamic tool filtering for context management - removes all tools except search_tools, then adds only relevant tools when queried"
# GENERATED BY METAPROGRAMMER - Safe to delete for testing
"""
SearchToolsBehavior provides dynamic tool filtering for context management.
It removes all tools except search_tools from the initial context and
adds only relevant tools when queried.
"""

from typing import Any, List, Dict
from behaviors.base import AgentBehavior
from behaviors.rule_of_two_types import RuleOfTwoProperty
import difflib


class SearchToolsBehavior(AgentBehavior):
    """
    Dynamic tool filtering for context management - removes all tools except search_tools,
    then adds only relevant tools when queried.

    Security: [] None (only reads agent's internal state/tools, not workspace files)
    """

    # Rule of Two: Empty (utility behavior for tool search)
    rule_of_two_properties = set()

    def __init__(self, workspace_manager=None, **kwargs):
        """
        Initialize behavior.

        Args:
            workspace_manager: Optional WorkspaceManager for file path resolution
            **kwargs: Additional parameters (ignored for extensibility)
        """
        self.workspace_manager = workspace_manager
        self._all_tools: List[Dict[str, Any]] = []
        self._active_tools: set[str] = set()

    def get_name(self) -> str:
        """
        Return unique behavior identifier.

        This name is used for logging and identification.

        Returns:
            Behavior name string (e.g., "SearchToolsBehavior")
        """
        return "SearchToolsBehavior"

    def get_tools(self) -> list[dict[str, Any]]:
        """
        Return tool definitions in OpenAI function format.

        Each tool must have:
        - name: Tool identifier
        - description: What the tool does
        - parameters: JSON Schema for tool arguments

        Returns:
            List of tool definition dicts
        """
        return [
            {
                "type": "function",
                "function": {
                    "name": "search_tools",
                    "description": "Search for tools by keyword or pattern. Returns tool names and descriptions matching the query. Only matching tools are added to context.",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "query": {
                                "type": "string",
                                "description": "Search query (keywords or pattern to match against tool names/descriptions)",
                            },
                            "max_results": {
                                "type": "integer",
                                "description": "Maximum number of matching tools to return (default: 10)",
                            },
                        },
                        "required": ["query"],
                    },
                },
            }
        ]

    def dispatch_tool(
        self,
        agent: Any,
        tool_name: str,
        args: dict[str, Any]
    ) -> dict[str, Any]:
        """
        Execute tool by name.

        Args:
            agent: Agent instance (access workspace, state, etc.)
            tool_name: Name of tool to execute
            args: Tool arguments from LLM

        Returns:
            Result dict with either:
            - {"result": value, "success": True} on success
            - {"error": message} on failure
        """
        if tool_name == "search_tools":
            try:
                query = args.get("query", "")
                max_results = args.get("max_results", 10)
                if not isinstance(query, str):
                    raise ValueError("query must be a string")
                if not isinstance(max_results, int) or max_results <= 0:
                    raise ValueError("max_results must be a positive integer")

                # ALWAYS query current tools (don't rely on cache)
                # This ensures we see tools added after initial context
                current_tools = agent.get_tools()

                matches = []
                query_lower = query.lower()
                for tool in current_tools:
                    func = tool.get("function", {})
                    name = func.get("name", "")
                    description = func.get("description", "")
                    if query_lower in name.lower() or query_lower in description.lower():
                        matches.append({"name": name, "description": description})
                        self._active_tools.add(name)
                        if len(matches) >= max_results:
                            break

                return {"result": matches, "success": True}
            except Exception as e:
                return {"error": str(e)}

        # Unknown tool - return error instead of calling super()
        return {"error": f"Unknown tool: {tool_name}"}

    def on_initial_context(
        self,
        agent: Any,
        context: list[dict[str, Any]]
    ) -> list[dict[str, Any]]:
        """
        Called once at agent startup.

        Filters out all tools except search_tools from the initial context.
        """
        # Store all tools for later use
        self._all_tools = agent.get_tools()

        # Build tool documentation for search_tools only
        tools = self.get_tools()
        if not tools:
            return context

        tool_docs = []
        for tool in tools:
            func = tool.get("function", {})
            name = func.get("name", "unknown")
            desc = func.get("description", "")
            params = func.get("parameters", {}).get("properties", {})
            required = func.get("parameters", {}).get("required", [])

            param_strs = []
            for param_name, param_spec in params.items():
                param_type = param_spec.get("type", "any")
                is_required = param_name in required
                if is_required:
                    param_strs.append(f"{param_name}: {param_type}")
                else:
                    param_strs.append(f"{param_name}?: {param_type}")

            param_sig = ", ".join(param_strs) if param_strs else ""
            tool_docs.append(f"  - {name}({param_sig}): {desc}")

        if tool_docs:
            tool_message = f"\n{self.get_name()} tools:\n" + "\n".join(tool_docs)
            return self.inject_user_message_after_system(context, tool_message)

        return context